name: clinical
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7
  uuid: ^4.5.1
  sqflite: ^2.4.1
  path: ^1.9.0
  intl: ^0.19.0
  crypto: ^3.0.6

  appointment_repository:
    path: packages/firebase_appointment_repository

  patient_repository:
    path: packages/firebase_patient_repository

  user_repository:
    path: packages/firebase_user_repository

  doctor_repository:
    path: packages/firebase_doctor_repository

  prescription_repository:
    path: packages/firebase_prescription_repository

  firebase_core: ^3.8.1
  font_awesome_flutter: ^10.8.0
  table_calendar: ^3.1.3
  http: ^1.2.2
  image_picker: ^1.1.2
  image_cropper: ^8.1.0
  cloud_firestore: ^5.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
  
  assets:
    - assets/
 