name: doctor_repository
description: "The repo that handles doctors."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  equatable: ^2.0.5
  cloud_firestore: ^5.1.0
  path: ^1.9.0
  rxdart: ^0.28.0
  firebase_storage: ^12.1.1

  clinical:
    path: C:/zeinab/clinical

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
